### ISSUE TITLE
Develop a timeline and checklist for completion

### ISSUE THREAD

**Issue by kbenoit** [quanteda/Text-Analysis-Using-R#4]
Develop a timeline for completion
- [ ] for writing chapters
- [ ] **quanteda.tidy** development and release
- [ ] Integration with transformers **flaiR**
